name: Linting and formatiing on PR
on:
  pull_request:
    branches:
      - "**"

jobs:
  Continuous-Integration:

    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Run linting check
        run: npm run lint

      - name: Run build
        run: npm run build
